### ISSUE TITLE
它来了，它来了， pandownload它又卷土重来了，百度网盘资源不限速下载！

### ISSUE THREAD

**Issue by liuqiangjian** [dylanbai8/BaiDuWangPan_SVIP_Share#1]
它来了，它来了， pandownload它又卷土重来了，百度网盘资源不限速下载！
一个pandownload倒下了，另一个pandownload又起来了，正义的力量无可阻挡！！！
[度老七官网](https://dulao7.com/)
通过上边那个网站去下载百度网盘里边的资源，不需要登录自己的百度账号，而且下载的时候不限速，个人实测家庭带宽每秒下载20多MB每秒，有群友在服务器上实测下载速度每秒60多MB，欢迎大家前来体验！

**Comment by dylanbai8** [comment]
你这个用的是别人的开源项目，请勿删除版权。

**Comment by liuqiangjian** [comment]
> 你这个是别人的开源项目，请勿删除版权。

原版的接口根本不稳，我找人重构了接口，数据库存在注入问题，都是我们自己修复的，源码是别人的没错，现在也就那层皮是拷贝别人的，原版的数据库查询采用的都是字符串直接拼接的

**Comment by liuqiangjian** [comment]
> 你这个是别人的开源项目，请勿删除版权。

还有重要的一点是，我并未拿去做任何盈利性质的事情，纯免费，也没搞什么赞助啊，加群获取密码啊那一类花里胡哨的

**Comment by dylanbai8** [comment]
引用了别人的代码就需要声明的，不是多和少、盈利不盈利的问题。你自己有二开、做公益当然好，但这是两码事。

**Comment by dylanbai8** [comment]
另外，你开小号 滥用 issue ，来我这里做推广。请停止这种行为
